import React, { useRef, useState, useEffect } from 'react';
import { loadSeries } from '../lib/chartData';

/**
 * The landing hero number.
 *
 * This component previously held its value as a literal char array
 * (['3','0','0',',','0','0','0']). That 300,000 traced to an illustrative
 * EXAMPLE in docs/07-editorial-content.md, not to any dataset, and it rendered
 * as the site's largest claim for months.
 *
 * So the number is no longer expressible as a literal. The component takes the
 * key of a generated series, fetches it, and renders whatever comes back. An
 * unsourced hero stays unrepresentable rather than merely discouraged: there is
 * no prop that accepts a number.
 *
 * The descriptor used to be {metric, geoLevel, yearFrom, yearTo} interpolated
 * into SQL here. That moved to pipeline/analysis/chart_data.py when DuckDB-WASM
 * came out of the browser, so the definition of this number now sits beside its
 * SQL rather than in a React prop.
 *
 * `fallback` is the server-rendered value, shown for the one fetch it takes to
 * load the series so the hero never blanks. It is passed from the page, which
 * cannot invent it either: index.astro reads it from headline_figures.json. If
 * the series disagrees with it, the series wins and we log; that mismatch means
 * the data moved and the page needs rebuilding.
 */

export interface HeroMetric {
  /**
   * Key of a series in public/data/charts/, generated by
   * pipeline/analysis/chart_data.py. Deliberately not a metric name and not a
   * value: the query that defines this number lives with the data.
   */
  dataKey: string;
  /** Server-rendered value, so the hero never renders empty. */
  fallback: number;
}

function groupDigits(value: number): string[] {
  // European convention per docs/05-design.md is a non-breaking space for the
  // thousands separator in Slovak. The landing hero is language-neutral digits,
  // so a comma is used for the English default; the separator is a single
  // character either way and the reveal treats it as one cell.
  return value.toLocaleString('en').split('');
}

export default function HeroCounter({ dataKey, fallback }: HeroMetric) {
  const ref = useRef<HTMLDivElement>(null);
  const [value, setValue] = useState<number>(fallback);
  const [visibleChars, setVisibleChars] = useState(0);

  // Fetch the series and render its single total. Reading one field off one row
  // is the only arithmetic this component does.
  useEffect(() => {
    let cancelled = false;
    async function resolve() {
      try {
        const rows = await loadSeries<{ total: number | null }>(dataKey);
        if (cancelled) return;
        const total = rows[0]?.total;
        if (total == null) {
          console.error(
            `HeroCounter: series "${dataKey}" carried no total. ` +
            'Keeping the server-rendered value.'
          );
          return;
        }
        const resolved = Math.round(Number(total));
        if (resolved !== fallback) {
          console.warn(
            `HeroCounter: series "${dataKey}" says ${resolved}, page was rendered ` +
            `with ${fallback}. Using the series. Rebuild the page.`
          );
        }
        setValue(resolved);
      } catch (err) {
        // Keep the server-rendered value rather than blanking the hero.
        console.error('HeroCounter: could not load the series, showing fallback.', err);
      }
    }
    resolve();
    return () => { cancelled = true; };
  }, [dataKey, fallback]);

  const chars = groupDigits(value);

  useEffect(() => {
    const prefersReduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (prefersReduced) {
      setVisibleChars(chars.length);
      return;
    }
    const interval = 1000 / chars.length;
    let step = 0;
    const timer = setInterval(() => {
      step++;
      setVisibleChars(step);
      if (step >= chars.length) clearInterval(timer);
    }, interval);
    return () => clearInterval(timer);
  }, [chars.length]);

  return (
    <div ref={ref} style={{
      fontFamily: 'var(--font-serif)',
      fontSize: 'clamp(80px, 16vw, 180px)',
      fontWeight: 400,
      color: 'var(--accent-primary)',
      letterSpacing: '-0.03em',
      lineHeight: 0.9,
      margin: 0,
      display: 'flex',
      justifyContent: 'center',
    }}>
      {chars.map((char, i) => (
        <span
          key={`${i}-${char}`}
          style={{
            display: 'inline-block',
            opacity: (chars.length - i) <= visibleChars ? 1 : 0,
            transition: 'opacity 0.12s ease',
          }}
        >
          {char}
        </span>
      ))}
    </div>
  );
}
