"""Extract the Slovak-relevant rows from the raw ACS tables.

    .venv/bin/python -m pipeline.transform.us_census_slovak

WHY THIS EXISTS. §3's prose quotes three American Community Survey figures, and
until now their only source in this repository was `data/raw/us_census/`, which is
gitignored along with the other 738 MB of raw data. That made those three figures
the one set of published claims on the site that nobody could re-check from a
clone: the numbers were in the prose, the evidence was on one laptop.

This writes the relevant rows, with their margins of error, variable codes and the
Census Bureau's own labels, to `data/processed/us_census_slovak.json`, which is
committed. Small enough to track, complete enough to verify the prose against.

WHAT THE FIGURES ARE FOR. §3's argument is that the diaspora cannot be counted on
one definition, and the United States is the sharpest case: ancestry and birthplace
differ there by a factor of about thirty. B04006 is self-reported ancestry, B05006
is place of birth. They are not two measurements of one quantity.

NOTE ON B05006. Its only relevant line is "Czechoslovakia (includes Czech Republic
and Slovakia)", so it cannot be split into a Slovak-born figure at all: the survey
does not offer one. That is why §3 uses a PUMS-derived figure for Slovak-born
instead, which this file cannot carry because the microdata is not held here. That
limitation is recorded in the output so it travels with the numbers.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

log = logging.getLogger(__name__)

REPO = Path(__file__).resolve().parents[2]
RAW = REPO / "data" / "raw" / "us_census"
OUT = REPO / "data" / "processed" / "us_census_slovak.json"

VINTAGE = "2023 ACS 5-year estimates"

# Variable codes carrying the lines §3 cites, resolved from the Census Bureau's own
# label files rather than guessed. The E suffix is the estimate, M the margin of
# error at 90 percent confidence.
WANTED = {
    "B04006_2023.json": {
        "B04006_070": "Slovak ancestry",
        "B04006_032": "Czechoslovakian ancestry",
        "B04006_031": "Czech ancestry",
        "B04006_001": "Total population reporting any ancestry",
    },
    "B05006_2023.json": {
        # The only Slovak-adjacent birthplace line. Not separable into Slovakia.
        "B05006_034": "Born in Czechoslovakia (includes Czech Republic and Slovakia)",
    },
}


def load_labels(table: str) -> dict[str, str]:
    path = RAW / f"{table}_labels.json"
    raw = json.loads(path.read_text(encoding="utf-8"))
    return {k: v.get("label", "") for k, v in raw["variables"].items() if isinstance(v, dict)}


def run() -> dict:
    if not RAW.exists():
        raise FileNotFoundError(
            f"{RAW} is missing. This step needs the raw ACS fetch: set CENSUS_API_KEY "
            f"in .env and run pipeline.fetch.us_census."
        )

    out: dict = {
        "_comment": "GENERATED by pipeline/transform/us_census_slovak.py. Do not edit by hand.",
        "vintage": VINTAGE,
        "geography": "United States, national",
        "note": (
            "Ancestry (B04006) and place of birth (B05006) are different quantities, "
            "not two measurements of one. B05006 offers no Slovakia line: its only "
            "relevant category is Czechoslovakia inclusive of both successor states, "
            "so a Slovak-born count cannot be taken from it. The Slovak-born figure "
            "quoted in section 3 is PUMS-derived and is NOT reproducible from this "
            "file, because the microdata is not held in this repository."
        ),
        "margin_of_error": "90 percent confidence, as published by the Census Bureau",
        "tables": {},
    }

    for filename, wanted in WANTED.items():
        table = filename.split("_")[0]
        rows = json.loads((RAW / filename).read_text(encoding="utf-8"))
        header, values = rows[0], rows[1]
        idx = {name: i for i, name in enumerate(header)}
        labels = load_labels(table)

        entries = {}
        for code, description in wanted.items():
            e_key, m_key = f"{code}E", f"{code}M"
            if e_key not in idx:
                raise KeyError(f"{filename}: {e_key} absent. Table layout changed.")
            estimate = int(values[idx[e_key]])
            raw_moe = int(values[idx[m_key]]) if m_key in idx else None
            # The Census Bureau encodes "not applicable" as -555555555 rather than
            # null. Passing that through as a margin of error would be a fabricated
            # number, which is exactly what this project does not do.
            moe = None if raw_moe is not None and raw_moe < 0 else raw_moe
            entries[code] = {
                "what": description,
                "census_label": labels.get(e_key, ""),
                "estimate": estimate,
                "margin_of_error": moe,
            }
            log.info("%s %s: %s (+/- %s)", table, code, f"{estimate:,}", moe)

        out["tables"][table] = entries

    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    return out


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    data = run()
    print()
    for table, entries in data["tables"].items():
        for code, e in entries.items():
            moe = f"+/- {e['margin_of_error']:,}" if e["margin_of_error"] is not None else "no MoE published"
            print(f"  {table} {code}  {e['estimate']:>12,}  {moe:>18}   {e['what']}")
    print(f"\n  written to {OUT.relative_to(REPO)}")
